create or replace function p_InsertBrevisContent(
  IN p_id VARCHAR(36),
  IN p_path VARCHAR(4096),
  IN p_contentType VARCHAR(255),
  IN p_headline TEXT,
  IN p_sectionId VARCHAR(255),
  IN p_sectionName VARCHAR(255),
  IN p_webPublicationDateISO VARCHAR(255),
  IN p_webPublicationDateTimestamp BIGINT,
  IN p_tags TEXT,
  IN p_webUrl VARCHAR(4096),
  IN p_standfirst VARCHAR(1024),
  IN p_authors TEXT,
  IN p_creatorName VARCHAR(255),
  IN p_byline VARCHAR(255),
  IN p_main TEXT,
  IN p_bodyText TEXT,
  IN p_bodyHtml TEXT,
  IN p_wordCount INT,
  IN p_productionOffice VARCHAR(255)
)
  returns table(
    brevis_content_id VARCHAR(36),
    brevis_content_path VARCHAR(4096),
    brevis_content_contentType VARCHAR(255),
    brevis_content_headline TEXT,
    brevis_content_sectionId VARCHAR(255),
    brevis_content_sectionName VARCHAR(255),
    brevis_content_webPublicationDateISO VARCHAR(255),
    brevis_content_webPublicationDateTimestamp BIGINT,
    brevis_content_tags TEXT,
    brevis_content_webUrl VARCHAR(4096),
    brevis_content_standfirst VARCHAR(1024),
    brevis_content_authors TEXT,
    brevis_content_creatorName VARCHAR(255),
    brevis_content_byline VARCHAR(255),
    brevis_content_main TEXT,
    brevis_content_bodyText TEXT,
    brevis_content_bodyHtml TEXT,
    brevis_content_wordCount INT,
    brevis_content_productionOffice VARCHAR(255)
  ) AS
$BODY$

  insert into
    brevis_content (
      id,
      path,
      contentType,
      headline,
      sectionId,
      sectionName,
      webPublicationDateISO,
      webPublicationDateTimestamp,
      tags,
      webUrl,
      standfirst,
      authors,
      creatorName,
      byline,
      main,
      bodyText,
      bodyHtml,
      wordCount,
      productionOffice
    ) values (
      p_id,
      p_path,
      p_contentType,
      p_headline,
      p_sectionId,
      p_sectionName,
      p_webPublicationDateISO,
      p_webPublicationDateTimestamp,
      p_tags::JSON,
      p_webUrl,
      p_standfirst,
      p_authors::JSON,
      p_creatorName,
      p_byline,
      p_main,
      p_bodyText,
      p_bodyHtml,
      p_wordCount,
      p_productionOffice
    ) on conflict (path) do update
      set
        path = p_path,
        contentType = p_contentType,
        headline = p_headline,
        sectionId = p_sectionId,
        sectionName = p_sectionName,
        webPublicationDateISO = p_webPublicationDateISO,
        webPublicationDateTimestamp = p_webPublicationDateTimestamp,
        tags = p_tags::JSON,
        webUrl = p_webUrl,
        standfirst = p_standfirst,
        authors = p_authors::JSON,
        creatorName = p_creatorName,
        byline = p_byline,
        main = p_main,
        bodyText = p_bodyText,
        bodyHtml = p_bodyHtml,
        wordCount = p_wordCount,
        productionOffice = p_productionOffice
    returning
      id,
      path,
      contentType,
      headline,
      sectionId,
      sectionName,
      webPublicationDateISO,
      webPublicationDateTimestamp,
      tags::TEXT,
      webUrl,
      standfirst,
      authors::TEXT,
      creatorName,
      byline,
      main,
      bodyText,
      bodyHtml,
      wordCount,
      productionOffice;

$BODY$
LANGUAGE sql;